### ISSUE TITLE
G

### ISSUE THREAD

**Issue by kagel** [kagel/jenkins-pr-comments-test#15]

**Comment by test-2016-07-06** [comment]
Current balance: 0.0000 ETH
![QR Code](http://localhost:3000/qr/kagel/jenkins-pr-comments-test/bounty/15/0074ddbf1d2311628ed2a5f7421cc07fc9debbae62a3a6ec499623e2d712a1d8/qr.png)
[http://localhost:3000](http://localhost:3000)
