### ISSUE TITLE
H

### ISSUE THREAD

**Issue by kagel** [kagel/jenkins-pr-comments-test#17]

**Comment by test-2016-07-06** [comment]
Current balance: 0.0000 ETH
![QR Code](http://139.162.11.12/qr/kagel/jenkins-pr-comments-test/bounty/17/d60f0c1e0188b669212f0e51ab0575081255d8cd9730703c195a0305f9e1108e/qr.png)
[http://localhost:3000](http://localhost:3000)

**Comment by test-2016-07-06** [comment]
![QR Code](http://139.162.11.12/qr/kagel/jenkins-pr-comments-test/bounty/17/d60f0c1e0188b669212f0e51ab0575081255d8cd9730703c195a0305f9e1108e/qr.png)

**Comment by test-2016-07-06** [comment]
Current balance: 0.0000 ETH
![QR Code](http://localhost:3000/qr/kagel/jenkins-pr-comments-test/bounty/17/d60f0c1e0188b669212f0e51ab0575081255d8cd9730703c195a0305f9e1108e/qr.png)
[http://localhost:3000](http://localhost:3000)

**Comment by test-2016-07-06** [comment]
Current balance: 0.0000 ETH
![QR Code](http://localhost:3000/qr/kagel/jenkins-pr-comments-test/bounty/17/d60f0c1e0188b669212f0e51ab0575081255d8cd9730703c195a0305f9e1108e/qr.png)
[http://localhost:3000](http://localhost:3000)

**Comment by test-2016-07-06** [comment]
Current balance: 0.0000 ETH
![QR Code](http://localhost:3000/qr/kagel/jenkins-pr-comments-test/bounty/17/d60f0c1e0188b669212f0e51ab0575081255d8cd9730703c195a0305f9e1108e/qr.png)
[http://localhost:3000](http://localhost:3000)

**Comment by test-2016-07-06** [comment]
Current balance: 0.0000 ETH
![QR Code](http://localhost:3000/qr/kagel/jenkins-pr-comments-test/bounty/17/d60f0c1e0188b669212f0e51ab0575081255d8cd9730703c195a0305f9e1108e/qr.png)
[http://localhost:3000](http://localhost:3000)
