### ISSUE TITLE
Z

### ISSUE THREAD

**Issue by kagel** [kagel/jenkins-pr-comments-test#19]

**Comment by test-2016-07-06** [comment]
Current balance: 0.0000 ETH
![QR Code](http://localhost:3000/qr/kagel/jenkins-pr-comments-test/bounty/19/b7a8af3b987a6491dab1e3dff8fb356f78d0691f610907b91a0a48895fd0697a/qr.png)
[http://localhost:3000](http://localhost:3000)

**Comment by test-2016-07-06** [comment]
Current balance: 0.0000 ETH
![QR Code](http://localhost:3000/qr/kagel/jenkins-pr-comments-test/bounty/19/b7a8af3b987a6491dab1e3dff8fb356f78d0691f610907b91a0a48895fd0697a/qr.png)
[http://localhost:3000](http://localhost:3000)
