### ISSUE TITLE
First sync takes days too complete both on testnet and public chai

### ISSUE THREAD

**Issue by kagel** [kagel/jenkins-pr-comments-test#38]

**Comment by test-2016-07-06** [comment]
Current balance: 1.00000000 ETH
![QR Code](http://commiteth.com/qr/kagel/jenkins-pr-comments-test/bounty/38/b441cdc67305b704f3f9cb36bb7c4c63524be238e32d86030e90c08fa9ffb534/qr.png)
[http://commiteth.com](http://commiteth.com)
